### ISSUE TITLE
Resilient simple value types?

### ISSUE THREAD

**Issue by abrownsword** [airbnb/ResilientDecoding#27]
I would really like to use your wrapper or something like it on my simple type fields too!  Things like Double, String, Int, etc.  If I'm decoding a JSON that doesn't have the given member in it, I just want to leave the field in my Swift struct set to whatever its default value is.

Is this possible to add?

**Comment by GeorgeLyon** [comment]
We don't support this out-of-the-box because "whatever the default value is" isn't obvious enough and clarity at point of use suffers as a result. 0 and the empty string seem like good candidates but if I saw something like `@Resilient var foo: String` I'd probably still double check with the documentation what the default behavior is, which is something I'd like to avoid.

There are two ways to address your use case:
The first is to create a `ResilientRawRepresentable` type with a primitive type as its `RawValue` and then specify a `static var decodingFallback: Self { <default value> }`. You would have to unwrap this value, but it makes it super obvious what the default value is.
The second way is better if the default value of your property is unique to the type being decoded. Then you can have a `@Resilient private var myOptionalProperty: Int?` and add a accessor `var myProperty: Int { myOptionalProperty ?? <default value> }`. You may also need to create coding keys to have `myOptionalProperty` map to the correct string key.

**Comment by abrownsword** [comment]
Hmmm... unfortunately neither of these is very attractive in my use case(s).  I have about a dozen different struct types (many nested within arrays in structs), and they have 5-30 simple fields (mostly Double, but some integer types and the occasional string).  All have a default value (i.e.    var fieldname : type = defaultvalue).  Wrapping them or adding an additional member to access them causes all sorts of issues, either with the code using them or with the toolchain (e.g. looking at values in the debugger).  It "uglyifies" the code terribly and requires active programmer intervention to add members... my goal here would be just to add a property wrapper to the line declaring the field and that's it.  I have an almost-but-not-quite-working solution from the BetterCodable project, but it doesn't work in practice for nested structs in arrays.
