### ISSUE TITLE
Support passthrough conformances for encoding and equatable

### ISSUE THREAD

**Issue by matthewcheok** [airbnb/ResilientDecoding#39]
Currently if we try to add the resilient property wrapper to a `Codable` struct, we're forced to supply our own conformances to `Encodable` and `Equatable` instead of being able to leverage compiler-supplied conformances. I think this can be resolved if we conditionally allow the `Resilient` wrapper to conform when the wrapped value also conforms to these protocols.

**Comment by fdiaz** [comment]
This is very similar to https://github.com/airbnb/ResilientDecoding/pull/38

cc @GeorgeLyon

**Comment by GeorgeLyon** [comment]
Resilient types are explicitly _not_ encodable because they lose information in the presence of errors (i.e. decoding and re-encoding a type may not yield the same data). For Trip Platform, the encodable requirement should be resolved by LosslessSerializable and if it isn't, then you can choose to ignore my warnings and add a conformance in your own project. 

For Equatable, the situation is similar. I believe we shouldn't be using equality with Resilient types (since the underlying data may not be equal). I consider this an anti-pattern, but if you really need to you can always enable it in your own code by writing an extension (but not encourage others to do the same).

**Comment by dfed** [comment]
Since this is a common request, it might be good to add a section to the README on how to check that successfully decoded responses are equal. In that section, you could also describe why pass through conformances aren't supported.

**Comment by GeorgeLyon** [comment]
This has been addressed in the readme.
